replicaCount: 1
image:
  repository: ghcr.io/aryzhykau/argocd-producer-demo
  pullPolicy: IfNotPresent
  tag: "sha-1fe8d0b"
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  host: argocd-producer-demo.local
  path: /
  pathType: Prefix
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
env:
  APP_VERSION: "0.1.0"
  KAFKA_BROKERS: "demo-cluster-kafka-bootstrap.strimzi.svc.cluster.local:9092"
  KAFKA_TOPIC: "demo-topic"
  BURST_SIZE: "50"
  BURST_INTERVAL_SECONDS: "30"
keda:
  enabled: false
autoscaling:
  enabled: false
