replicaCount: 1
image:
  repository: ghcr.io/aryzhykau/argocd-producer-demo
  pullPolicy: IfNotPresent
  tag: "sha-ffc7643"
ingress:
  enabled: false
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
env:
  APP_VERSION: "0.1.0"
  KAFKA_BROKERS: "demo-cluster-kafka-bootstrap.strimzi.svc.cluster.local:9092"
  KAFKA_TOPIC: "demo-topic"
  BURST_SIZE: "50"
  BURST_INTERVAL_SECONDS: "30"
keda:
  enabled: false
autoscaling:
  enabled: false
