apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-service-demo-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/aryzhykau/argostate-demo.git
    targetRevision: HEAD
    path: charts/argocd-service-demo
    helm:
      valueFiles:
        - ../../../apps/argocd-service-demo/dev/values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-service-demo

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
